# Path sets for pathfinder

[[Paths]]
path = "$ANDROID_STO_ROOT/bin"
aspects = ["android-studio", "android", "user"]

[[Paths]]
path = "$ANDROID_SDK_ROOT/tools/bin"
aspects = ["android-sdk-tools", "android-sdk", "android", "user"]

[[Paths]]
path = "$ANDROID_SDK_ROOT/build-tools/26.0.0"
aspects = ["android-build-tools", "android-sdk", "android", "user"]

[[Paths]]
path = "$ANDROID_SDK_ROOT/platform-tools"
aspects = ["android-platform-tools", "android-sdk", "android", "user"]

[[Paths]]
path = "$ANDROID_SDK_ROOT/emulator"
aspects = ["android-emulator", "android-sdk", "android", "user"]

[[Paths]]
path = "$ANACONDA_HOME/bin"
aspects = ["anaconda", "user"]

[[Paths]]
path = "$HOME/.cargo/bin"
aspects = ["rust", "user", "default"]

[[Paths]]
path = "$HOME/.gem/ruby/2.4.0/bin"
aspects = ["ruby", "user", "default"]

[[Paths]]
path = "$HOME/.npm-global/bin"
aspects = ["npm", "user", "default"]

[[Paths]]
path = "$HOME/.zplug/repos/zplug/zplug/bin"
aspects = ["zplug", "user", "default"]

[[Paths]]
path = "$HOME/.zplug/bin"
aspects = ["zplug", "user", "default"]

[[Paths]]
path = "$HOME/.luarocks/bin"
aspects = ["lua", "user", "default"]

[[Paths]]
path = "$HOME/.local/bin"
aspects = ["userbin", "user", "default"]

[[Paths]]
path = "/usr/bin"
aspects = ["system", "default"]

[[Paths]]
path = "/usr/local/sbin"
aspects = ["system", "default"]

[[Paths]]
path = "/usr/local/bin"
aspects = ["system", "default"]

[[Paths]]
path = "/usr/lib/jvm/default/bin"
aspects = ["java", "system", "default"]

[[Paths]]
path = "/usr/bin/site_perl"
aspects = ["perl", "system", "default"]

[[Paths]]
path = "/usr/bin/vendor_perl"
aspects = ["perl", "system", "default"]

[[Paths]]
path = "/usr/bin/core_perl"
aspects = ["perl", "system", "default"]
